### ISSUE TITLE
[charts] `bmrg-flow-apps-flow` ingress definition is invalid

### ISSUE THREAD

**Issue by aiciobanu** [boomerang-io/roadmap#358]
### Describe the bug

`bmrg-flow-apps-flow` ingress template is invalid. `annotations.kubernetes.io/ingress.class` and `spec.ingressClassName` cannot be used at the same time

### What project does this issue relate to?

Boomerang Flow

### To Reproduce

 1. Have a Kubernetes platform
 2. Deploy `bmrg-flow-4.13.3` helm chart

### Environment

Kubernetes platforms used:
 - k3d (k3s versions 1.21 and 1.22)
 - IBM Kubernetes Service v1.21

**Comment by tlawrie** [comment]
Hey @aiciobanu I checked with @morarucostel and @gchickma on the removal of the annotation in the last release 3.10. It was determined it was no longer needed to be supported as support for the annotation has been dropped many versions before, and I think has been supported since Kube 1.19 or 1.21

It would be preferable to not have to have support for it.

**Comment by aiciobanu** [comment]
@tlawrie Closed the first PR and made a new one that removes the annotation
