### ISSUE TITLE
Merge in latest Twilio release

### ISSUE THREAD

**Issue by tlawrie** [boomerang-io/roadmap#61]
## Change

- For our current certified twilio tasks we utilize some custom changes which have now been merged upstream -> https://github.com/twilio/twilio-node/pull/590. Next time there is a Twilio release including this change we need to update our Workers to use that and retest.

**Comment by morarucostel** [comment]
@tlawrie The latest SDK build includes the fix you pushed. 
I've updated the flow worker to remove the manual fix and rely on the latest 3.57.0 twilio version. 

Build the new docker image and pushed, `boomerangio/worker-flow:2.5.29` .
The only thing remaining is to test. 

Since we are not introducing anything new, I believe we can override the exising Task version.
